// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator Do not modify this file
 * See generator home page at:
 * http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package dao.model.builders.measures;

import dao.model.measures.BloodPressure;

import java.util.Date;

public class BloodPressureBuilder {

    private int systolic;

    private int diastolic;

    private int pulse;

    private Date occurrence;

    private String description;

    public BloodPressureBuilder withSystolic(int systolic) {
        this.systolic = systolic;
        return this;
    }

    public BloodPressureBuilder withDiastolic(int diastolic) {
        this.diastolic = diastolic;
        return this;
    }

    public BloodPressureBuilder withPulse(int pulse) {
        this.pulse = pulse;
        return this;
    }

    public BloodPressureBuilder withOccurrence(Date occurrence) {
        this.occurrence = occurrence;
        return this;
    }

    public BloodPressureBuilder withDescription(String description) {
        this.description = description;
        return this;
    }

    public BloodPressure build() {
        BloodPressure bloodPressure = new BloodPressure();
        bloodPressure.setSystolic(this.systolic);
        bloodPressure.setDiastolic(this.diastolic);
        bloodPressure.setPulse(this.pulse);
        bloodPressure.setOccurrence(this.occurrence);
        bloodPressure.setDescription(this.description);
        return bloodPressure;
    }
}

